"use client"

import { Form } from "@/components/ui/form"
import WACCResults from "./WACCResults"
import { buildWaccResult } from "@/lib/preview-wacc"
import { useCalculator } from "./calculator/useCalculator"
import { ReportIdentitySection } from "./calculator/ReportIdentitySection"
import { CountrySectorSection } from "./calculator/CountrySectorSection"
import { CapitalStructureSection } from "./calculator/CapitalStructureSection"
import { ICRSection } from "./calculator/ICRSection"
import { CostOfEquitySection } from "./calculator/CostOfEquitySection"
import { CostOfDebtSection } from "./calculator/CostOfDebtSection"
import { LiveWaccBar } from "./calculator/LiveWaccBar"
import { PrintReport } from "./calculator/PrintReport"

export interface FormValues {
  companyName: string
  asOfDate: string
  equityRatio: number
  debtRatio: number
  riskFreeRate: number
  beta: number
  marketRiskPremium: number
  additionalRisk: number
  sizePremium: number
  marketCap: number
  costOfDebt: number
  taxRate: number
  spreadRate: number
  debtRiskFreeRate: number
  ebit?: number
  interestExpense?: number
  companyType?: string
  country: string
  sector: string
  taxCountry?: string
  isAutoCalculated: boolean
}

export default function Calculator() {
  const {
    form,
    icr,
    handleCountryChange,
    handleSectorChange,
    updateICR,
    updateRatios,
  } = useCalculator()

  const values = form.watch()
  const result = buildWaccResult(values)

  return (
    <div className="space-y-8 print:space-y-6">
      <PrintReport values={values} icr={icr} result={result} />

      <Form {...form}>
        <form
          onSubmit={(event) => event.preventDefault()}
          className="space-y-6 print:hidden"
        >
          <ReportIdentitySection form={form} />

          <CountrySectorSection
            form={form}
            onCountryChange={handleCountryChange}
            onSectorChange={handleSectorChange}
          />

          <ICRSection form={form} updateICR={updateICR} icr={icr} />

          <CapitalStructureSection
            form={form}
            updateRatios={updateRatios}
            icr={icr}
          />

          <CostOfEquitySection form={form} />

          <CostOfDebtSection form={form} updateICR={updateICR} />
        </form>
      </Form>

      {result && <WACCResults result={result} />}

      <p className="hidden print:block border-t border-zinc-200 pt-3 text-[10px] leading-relaxed text-zinc-500">
        Sources: Fernandez (2025) market risk premia; Damodaran industry betas;
        Kroll size premia (2025). Levered beta uses Hamada (1972)
        with β<sub>D</sub> = 0. Generated by wacc.less.style.
      </p>

      <LiveWaccBar result={result} />
    </div>
  )
}
