import { damodaranSeo, waccVsEquitySeo } from "@/lib/site"

export interface ComparisonRow {
  topic: string
  equity: string
  wacc: string
}

export interface RelatedGuide {
  href: string
  title: string
  body: string
}

export const waccVsEquityRows: ComparisonRow[] = [
  {
    topic: "Who must be paid",
    equity: "Only the owners (shareholders)",
    wacc: "Owners and lenders, in one blended rate",
  },
  {
    topic: "What it measures",
    equity: "The return owners expect for the risk they take",
    wacc: "The average cost of all the money used by the company",
  },
  {
    topic: "Which cash flows it fits",
    equity: "Cash that belongs only to owners: dividends or profit after interest",
    wacc: "Cash generated by the business before paying lenders",
  },
  {
    topic: "Typical use",
    equity: "Valuing an equity stake, or a project funded only with equity",
    wacc: "Valuing the whole company, or a project funded with equity and debt",
  },
  {
    topic: "If the company borrows more",
    equity: "Owners usually demand a higher return, because risk rises",
    wacc: "The average can fall at first, then rise if debt becomes expensive",
  },
]

export const relatedGuides: RelatedGuide[] = [
  {
    href: "/guide",
    title: "WACC guide",
    body: "Formula, CAPM, levered beta, cost of debt, and the data behind the calculator.",
  },
  {
    href: waccVsEquitySeo.path,
    title: "WACC vs cost of equity",
    body: "The difference in plain terms, when to use each rate, and a worked example.",
  },
  {
    href: damodaranSeo.path,
    title: "Damodaran WACC calculator",
    body: "How sector betas, country tax rates, and default spreads enter the model.",
  },
]

export function relatedGuidesExcept(path: string) {
  return relatedGuides.filter((item) => item.href !== path)
}